### ISSUE TITLE
Using new_resource.path attribute leads to crashes

### ISSUE THREAD

**Issue by BarthV** [phbergsmann/chef-locales#14]
Ohai,

I'm running ubuntu 12.04 without any language pack.
Right after `include_recipe "locales"` (which is OK), i'm trying to add some other locales to the system.

Compiled resource :

```
locales("Setting available locales") do
  action :add
  retries 0
  retry_delay 2
  cookbook_name "my-cookbook"
  recipe_name "locale"
  locales ["en_US.UTF-8", "fr_FR.UTF-8", "en_GB.UTF-8"]
  utf8 true
end
```

leads to :

```
================================================================================
Error executing action `add` on resource 'locales[Setting available locales]'
================================================================================

NoMethodError
-------------
undefined method `close' for nil:NilClass

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/locales/providers/default.rb:73:in `ensure in file_append_line'
/var/chef/cache/cookbooks/locales/providers/default.rb:73:in `file_append_line'
/var/chef/cache/cookbooks/locales/providers/default.rb:11:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/locales/providers/default.rb:7:in `each'
/var/chef/cache/cookbooks/locales/providers/default.rb:7:in `block in class_from_file'
```

https://github.com/phbergsmann/chef-locales/blob/master/providers/default.rb#L70 : `new_resource.path` is not defined neither in resource nor in provider file.
We thus see that the def fails to create and write to  `/etc/locale.gen` file.

Maybe you wanted to write `path` instead ? I'll try to write, test and PR a fix for this.

**Comment by BarthV** [comment]
@guilhem PR #13 fixed this. So i'll switch to this branch.
It would be kind to review this one :) :up: for him.
